package com.craftinginterpreters.lox;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static com.craftinginterpreters.lox.TokenType.*;


class Parser {

    private final List<Token> tokens;

    private int current = 0;


    Parser(List<Token> tokens) {
        this.tokens = tokens;
    }

    /**
     * Parses a sequence of statements from the source code.
     *
     * This method is responsible for parsing a series of statements from the source code.
     * It continues parsing until it reaches the end of the input. Each statement is
     * generated by the `declaration()` method, and the parsed statements are collected
     * into a list.
     *
     * @return A list of parsed statements representing the program's syntax tree.
     * @see Stmt
     */
    List<Stmt> parse() {
        List<Stmt> statements = new ArrayList<>();
        while (!isAtEnd()) {
            statements.add(declaration());
        }

        return statements;
    }

    /**
     * Parses an expression from the source code.
     *
     * This method is responsible for parsing an expression from the source code. It delegates
     * the parsing to the `assignment()` method, which handles assignment expressions, binary
     * expressions, and other expression types.
     *
     * @return The parsed expression as an instance of the `Expr` class.
     * @see Expr
     */
    private Expr expression() {
        return assignment();
    }

    /**
     * Parses a declaration statement from the source code.
     *
     * This method is responsible for parsing various types of declaration statements,
     * including class declarations, function declarations, and variable declarations.
     * It uses the `match()` method to identify the type of declaration and delegates
     * the parsing to corresponding methods. In case of a parsing error, it attempts
     * to synchronize the parsing process and returns null.
     *
     * @return A parsed declaration statement, represented as an instance of the `Stmt` class,
     *         or null if a parsing error occurs.
     * @see Stmt
     * @see ParseError
     */
    private Stmt declaration() {
        try {
            if (match(CLASS)) return classDeclaration();
            if (match(FUN)) return function("function");
            if (match(VAR)) return varDeclaration();

            return statement();
        } catch (ParseError error) {
            synchronize();
            return null;
        }
    }

    /**
     * Parses a class declaration within the source code.
     *
     * This method is responsible for parsing a class declaration in the source code.
     * It expects a class name followed by a class body enclosed in '{' and '}' braces.
     * Inside the class body, it parses and collects a list of methods using the "function" method
     * until it encounters '}' or reaches the end of the input.
     *
     * @return A parsed class declaration statement, represented as a Stmt.Class object.
     * @throws ParseError If there are syntax errors in the class declaration.
     */
    private Stmt classDeclaration() {
        Token name = consume(IDENTIFIER, "Expect class name.");
        consume(LEFT_BRACE, "Expect '{' before class body.");

        List<Stmt.Function> methods = new ArrayList<>();
        while (!check(RIGHT_BRACE) && !isAtEnd()) {
            methods.add(function("method"));
        }

        consume(RIGHT_BRACE, "Expect '}' after class body.");

        return new Stmt.Class(name, methods);
    }

    /**
     * Parses a statement from the source code.
     *
     * This method is responsible for parsing various types of statements, including
     * for loops, if statements, return statements, while loops, and block statements.
     * It determines the type of statement by using the `match()` method and delegates
     * the parsing to corresponding methods. If none of the recognized statement types
     * match, it parses an expression statement.
     *
     * @return A parsed statement, represented as an instance of the `Stmt` class.
     * @see Stmt
     */
    private Stmt statement() {
        if (match(FOR)) return forStatement();
        if (match(IF)) return ifStatement();
        if (match(RETURN)) return returnStatement();
        if (match(WHILE)) return whileStatement();
        if (match(LEFT_BRACE)) return new Stmt.Block(block());

        return expressionStatement();
    }

    /**
     * Parses a 'for' loop statement from the source code.
     *
     * This method is responsible for parsing a 'for' loop statement, which consists of
     * an initializer, a condition, an increment expression, and a loop body. The initializer,
     * condition, and increment expressions are optional. It constructs the corresponding
     * AST nodes for the 'for' loop based on the parsed components.
     *
     * @return A parsed 'for' loop statement, represented as an instance of the `Stmt` class.
     * @see Stmt
     * @see Expr
     */
    private Stmt forStatement() {
        consume(LEFT_PAREN, "Expect '(' after 'for'.");

        Stmt initializer;
        if (match(SEMICOLON)) {
            initializer = null;
        } else if (match(VAR)) {
            initializer = varDeclaration();
        } else {
            initializer = expressionStatement();
        }

        Expr condition = null;
        if (!check(SEMICOLON)) {
            condition = expression();
        }
        consume(SEMICOLON, "Expect ';' after loop condition.");

        Expr increment = null;
        if (!check(RIGHT_PAREN)) {
            increment = expression();
        }
        consume(RIGHT_PAREN, "Expect ')' after for clauses.");
        Stmt body = statement();

        if (increment != null) {
            body = new Stmt.Block(
                    Arrays.asList(
                            body,
                            new Stmt.Expression(increment)
                    )
            );
        }

        if (condition == null) condition = new Expr.Literal(true);
        body = new Stmt.While(condition, body);

        if (initializer != null) {
            body = new Stmt.Block(Arrays.asList(initializer, body));
        }

        return body;
    }

    /**
     * Parses an 'if' statement from the source code.
     *
     * This method is responsible for parsing an 'if' statement, which consists of a condition,
     * a then-branch, and an optional else-branch. It constructs the corresponding AST node for
     * the 'if' statement based on the parsed components.
     *
     * @return A parsed 'if' statement, represented as an instance of the `Stmt` class.
     * @see Stmt
     * @see Expr
     */
    private Stmt ifStatement() {
        consume(LEFT_PAREN, "Expect '(' after 'if'.");
        Expr condition = expression();
        consume(RIGHT_PAREN, "Expect ')' after if condition.");

        Stmt thenBranch = statement();
        Stmt elseBranch = null;
        if (match(ELSE)) {
            elseBranch = statement();
        }

        return new Stmt.If(condition, thenBranch, elseBranch);
    }

    /**
     * Equality expr.
     *
     * @return the expr
     */
    private Expr equality() {
        Expr expr = comparison();

        while (match(BANG_EQUAL, EQUAL_EQUAL)) {
            Token operator = previous();
            Expr right = comparison();
            expr = new Expr.Binary(expr, operator, right);
        }

        return expr;
    }

    /* Binary Operations */

    /**
     * Comparison expr.
     *
     * @return the expr
     */
    private Expr comparison() {
        Expr expr = term();

        while (match(GREATER, GREATER_EQUAL, LESS, LESS_EQUAL)) {
            Token operator = previous();
            Expr right = term();
            expr = new Expr.Binary(expr, operator, right);
        }

        return expr;
    }

    /**
     * Term expr.
     *
     * @return the expr
     */
    private Expr term() {
        Expr expr = factor();

        while (match(MINUS, PLUS)) {
            Token operator = previous();
            Expr right = factor();
            expr = new Expr.Binary(expr, operator, right);
        }

        return expr;
    }

    /**
     * Factor expr.
     *
     * @return the expr
     */
    private Expr factor() {
        Expr expr = unary();

        while (match(SLASH, STAR)) {
            Token operator = previous();
            Expr right = unary();
            expr = new Expr.Binary(expr, operator, right);
        }

        return expr;
    }

    /**
     * Unary expr.
     *
     * @return the expr
     */
    private Expr unary() {
        if (match(BANG, MINUS)) {
            Token operator = previous();
            Expr right = unary();
            return new Expr.Unary(operator, right);
        }

        return call();
    }

    /**
     * Finish call expr.
     *
     * @param callee the callee
     * @return the expr
     */
    private Expr finishCall(Expr callee) {
        List<Expr> arguments = new ArrayList<>();
        if (!check(RIGHT_PAREN)) {
            do {
                if (arguments.size() >= 255) {
                    error(peek(), "Can't have more than 255 arguments.");
                }
                arguments.add(expression());
            } while (match(COMMA));
        }

        Token paren = consume(RIGHT_PAREN, "Expect ')' after arguments.");

        return new Expr.Call(callee, paren, arguments);
    }

    /**
     * Call expr.
     *
     * @return the expr
     */
    private Expr call() {
        Expr expr = primary();

        while (true) {
            if (match(LEFT_PAREN)) {
                expr = finishCall(expr);
            } else if (match(DOT)) {
                Token name = consume(IDENTIFIER, "Expect property name after '.'.");
                expr = new Expr.Get(expr, name);
            } else {
                break;
            }
        }

        return expr;
    }

    /**
     * Primary expr.
     *
     * @return the expr
     */
    private Expr primary() {
        if (match(FALSE)) return new Expr.Literal(false);
        if (match(TRUE)) return new Expr.Literal(true);
        if (match(NIL)) return new Expr.Literal(null);

        if (match(NUMBER, STRING)) {
            return new Expr.Literal(previous().literal);
        }

        if (match(THIS)) return new Expr.This(previous());

        if (match(IDENTIFIER)) {
            return new Expr.Variable(previous());
        }

        if (match(LEFT_PAREN)) {
            Expr expr = expression();
            consume(RIGHT_PAREN, "Expect ')' after expression.");
            return new Expr.Grouping(expr);
        }
        throw error(peek(), "Expect expression");
    }

    /**
     * Print statement stmt.
     *
     * @return the stmt
     */
    private Stmt printStatement() {
        Expr value = expression();
        consume(SEMICOLON, "Expect ';' after value.");
        return new Stmt.Print(value);
    }

    /**
     * Return statement stmt.
     *
     * @return the stmt
     */
    private Stmt returnStatement() {
        Token keyword = previous();
        Expr value = null;
        if (!check(SEMICOLON)) {
            value = expression();
        }

        consume(SEMICOLON, "Expect ';' after return value.");
        return new Stmt.Return(keyword, value);
    }

    /* Helper Methods */

    /**
     * Var declaration stmt.
     *
     * @return the stmt
     */
    private Stmt varDeclaration() {
        Token name = consume(IDENTIFIER, "Expect variable name.");

        Expr initializer = null;
        if (match(EQUAL)) {
            initializer = expression();
        }

        consume(SEMICOLON, "Expect ';' after variable declaration.");
        return new Stmt.Var(name, initializer);
    }

    /**
     * While statement stmt.
     *
     * @return the stmt
     */
    private Stmt whileStatement() {
        consume(LEFT_PAREN, "Expect '(' after 'while'.");
        Expr condition = expression();
        consume(RIGHT_PAREN, "Expect ')' after condition.");
        Stmt body = statement();

        return new Stmt.While(condition, body);
    }

    /**
     * Expression statement stmt.
     *
     * @return the stmt
     */
    private Stmt expressionStatement() {
        Expr expr = expression();
        consume(SEMICOLON, "Expect ';' after expression.");
        return new Stmt.Expression(expr);
    }

    /**
     * Function stmt . function.
     *
     * @param kind the kind
     * @return the stmt . function
     */
    private Stmt.Function function(String kind) {
        Token name = consume(IDENTIFIER, "Expect " + kind + "name.");
        consume(LEFT_PAREN, "Expect '(' after " + kind + " name.");
        List<Token> parameters = new ArrayList<>();
        if (!check(RIGHT_PAREN)) {
            do {
                if (parameters.size() >= 255) {
                    error(peek(), "Can't have more than 255 parameters.");
                }

                parameters.add(
                        consume(IDENTIFIER, "Expect parameter name.")
                );
            } while (match(COMMA));
        }
        consume(RIGHT_PAREN, "Expect ')' after parameters.");

        consume(LEFT_BRACE, "Expect '{' before " + kind + " body.");
        List<Stmt> body = block();
        return new Stmt.Function(name, parameters, body);
    }

    /**
     * Block list.
     *
     * @return the list
     */
    private List<Stmt> block() {
        List<Stmt> statements = new ArrayList<>();

        while (!check(RIGHT_BRACE) && !isAtEnd()) {
            statements.add(declaration());
        }

        consume(RIGHT_BRACE, "Expect '}' after block.");
        return statements;
    }

    /**
     * Assignment expr.
     *
     * @return the expr
     */
    private Expr assignment() {
        Expr expr = or();

        if (match(EQUAL)) {
            Token equals = previous();
            Expr value = assignment();

            if (expr instanceof Expr.Variable) {
                Token name = ((Expr.Variable) expr).name;
                return new Expr.Assign(name, value);
            } else if (expr instanceof Expr.Get) {
                Expr.Get get = (Expr.Get)expr;
                return new Expr.Set(get.object, get.name, value);
            }

            error(equals, "Invalid assignment target.");
        }

        return expr;
    }

    /**
     * Or expr.
     *
     * @return the expr
     */
    private Expr or() {
        Expr expr = and();

        while (match(OR)) {
            Token operator = previous();
            Expr right = and();
            expr = new Expr.Logical(expr, operator, right);
        }

        return expr;
    }

    /**
     * And expr.
     *
     * @return the expr
     */
    private Expr and() {
        Expr expr = equality();

        while (match(AND)) {
            Token operator = previous();
            Expr right = equality();
            expr = new Expr.Logical(expr, operator, right);
        }

        return expr;
    }

    /**
     * Match boolean.
     *
     * @param types the types
     * @return the boolean
     */
    private boolean match(TokenType... types) {
        for (TokenType type : types) {
            if (check(type)) {
                advance();
                return true;
            }
        }

        return false;
    }

    /**
     * Consume token.
     *
     * @param type    the type
     * @param message the message
     * @return the token
     */
    private Token consume(TokenType type, String message) {
        if (check(type)) return advance();

        throw error(peek(), message);
    }

    /**
     * Check boolean.
     *
     * @param type the type
     * @return the boolean
     */
    private boolean check(TokenType type) {
        if (isAtEnd()) return false;
        return peek().type == type;
    }

    /**
     * Advance token.
     *
     * @return the token
     */
    private Token advance() {
        if (!isAtEnd()) current++;
        return previous();
    }

    /**
     * Is at end boolean.
     *
     * @return the boolean
     */
    private boolean isAtEnd() {
        return peek().type == EOF;
    }

    /**
     * Peek token.
     *
     * @return the token
     */
    private Token peek() {
        return tokens.get(current);
    }

    /**
     * Previous token.
     *
     * @return the token
     */
    private Token previous() {
        return tokens.get(current - 1);
    }

    /**
     * Error parse error.
     *
     * @param token   the token
     * @param message the message
     * @return the parse error
     */
    private ParseError error(Token token, String message) {
        Lox.error(token, message);
        return new ParseError();
    }

    /**
     * Synchronize.
     */
    private void synchronize() {
        advance();

        while (!isAtEnd()) {
            if (previous().type == SEMICOLON) return;

            switch (peek().type) {
                case CLASS,
                        FUN,
                        VAR,
                        FOR,
                        IF,
                        WHILE,
                        RETURN -> {
                    return;
                }
            }

            advance();
        }
    }

    /**
     * The type Parse error.
     */
    private static class ParseError extends RuntimeException {
    }

}
